### ISSUE TITLE
Exploration: what are the common failure modes of minio?

### ISSUE THREAD

**Issue by DnPlas** [canonical/minio-operator#212]
### Context

We need to understand what the [common failure modes](https://docs.aws.amazon.com/whitepapers/latest/aws-outposts-high-availability-design/thinking-in-terms-of-failure-modes.html) are for this component to be able to create alert rules that can make them obvious to users.

Please note this is related to https://github.com/canonical/kfp-operators/issues/693

### What needs to get done

1. Understand what common failures does this component have
2. Document them
3. Draft an idea of the alerts for the failures

### Definition of Done

Common failure modes are documented for this component and that information helps the team to understand which alerts to add.

**Comment by misohu** [comment]
I have deplloyed minio with cos lite and identiffied following list of metrics we are gathering for the minio charm (descriptions of each metric can be found [here](https://min.io/docs/minio/linux/operations/monitoring/metrics-v2.html#cluster-metrics) )

```
minio_cluster_disk_free_inodes{}
minio_cluster_nodes_offline_total{}
minio_cluster_nodes_online_total{}
minio_inter_node_traffic_errors_total{}
minio_inter_node_traffic_received_bytes{}
minio_inter_node_traffic_sent_bytes{}
minio_node_disk_free_bytes{}
minio_node_disk_total_bytes{}
minio_node_disk_used_bytes{}
minio_node_file_descriptor_limit_total{}
minio_node_file_descriptor_open_total{}
minio_node_go_routine_total{}
minio_node_ilm_expiry_pending_tasks{}
minio_node_ilm_transition_active_tasks{}
minio_node_ilm_transition_pending_tasks{}
minio_node_io_rchar_bytes{}
minio_node_io_read_bytes{}
minio_node_io_wchar_bytes{}
minio_node_io_write_bytes{}
minio_node_process_cpu_total_seconds{}
minio_node_process_resident_memory_bytes{}
minio_node_process_starttime_seconds{}
minio_node_process_uptime_seconds{}
minio_node_syscall_read_total{}
minio_node_syscall_write_total{}
minio_s3_requests_errors_total{}
minio_s3_requests_inflight_total{}
minio_s3_requests_rejected_auth_total{}
minio_s3_requests_rejected_header_total{}
minio_s3_requests_rejected_invalid_total{}
minio_s3_requests_rejected_timestamp_total{}
minio_s3_requests_total{}
minio_s3_requests_waiting_total{}
minio_s3_time_ttfb_seconds_distribution{}
minio_s3_traffic_received_bytes{}
minio_s3_traffic_sent_bytes{}
minio_software_commit_info{}
minio_software_version_info{}
promhttp_metric_handler_requests_in_flight{}
promhttp_metric_handler_requests_total{}
up{}
scrape_duration_seconds{}
scrape_samples_scraped{}
scrape_samples_post_metric_relabeling{}
scrape_series_added{}
```

## Common Failure Modes for MinIO and Prometheus Alert Rules

### 1. **Disk or Storage Issues**

- **Failure Mode**: If the MinIO disk is running out of space, it can result in the inability to write new data or cause performance issues.

  **Relevant Metrics**:
  - `minio_node_disk_free_bytes`
  - `minio_node_disk_used_bytes`
  - `minio_node_disk_total_bytes`
  - `minio_cluster_disk_free_inodes`

  **Alert Examples**:
  
  - **Alert for Low Disk Space** (less than 10GB free):
    ```yaml
    - alert: MinIO_Low_Disk_Space
      expr: minio_node_disk_free_bytes < 10 * 1024 * 1024 * 1024
      for: 5m
      labels:
        severity: critical
      annotations:
        description: "MinIO node has less than 10GB of free disk space."
    ```

  - **Alert for High Disk Usage** (more than 90% used):
    ```yaml
    - alert: MinIO_High_Disk_Usage
      expr: (minio_node_disk_used_bytes / minio_node_disk_total_bytes) > 0.9
      for: 5m
      labels:
        severity: high
      annotations:
        description: "MinIO node has over 90% of its disk space used."
    ```

  - **Alert for Disk I/O Errors**:
    ```yaml
    - alert: MinIO_Disk_IO_Errors
      expr: minio_node_disk_errors_total > 0
      for: 5m
      labels:
        severity: high
      annotations:
        description: "There have been {{ $value }} disk I/O errors on MinIO node."
    ```

---

### 2. **S3 Request Failures**

- **Failure Mode**: Errors in processing S3 requests can indicate internal issues, client misconfigurations, or network problems that could impact MinIO's ability to serve data.

  **Relevant Metrics**:
  - `minio_s3_requests_errors_total`
  - `minio_s3_requests_rejected_auth_total`
  - `minio_s3_requests_rejected_header_total`
  - `minio_s3_requests_rejected_invalid_total`
  - `minio_s3_requests_rejected_timestamp_total`

  **Alert Examples**:
  
  - **Alert for High Number of S3 Errors** (more than 100 errors):
    ```yaml
    - alert: MinIO_S3_Request_Errors
      expr: minio_s3_requests_errors_total > 100
      for: 5m
      labels:
        severity: high
      annotations:
        description: "MinIO has encountered more than 100 S3 request errors."
    ```

  - **Alert for Auth Failures on S3 Requests**:
    ```yaml
    - alert: MinIO_S3_Request_Auth_Failures
      expr: minio_s3_requests_rejected_auth_total > 50
      for: 5m
      labels:
        severity: high
      annotations:
        description: "MinIO has encountered more than 50 authentication failures in S3 requests."
    ```

  - **Alert for Invalid S3 Requests**:
    ```yaml
    - alert: MinIO_S3_Request_Invalid
      expr: minio_s3_requests_rejected_invalid_total > 50
      for: 5m
      labels:
        severity: high
      annotations:
        description: "MinIO has rejected more than 50 invalid S3 requests."
    ```

---

### 3. **High Latency in S3 Requests**

- **Failure Mode**: High latency in serving S3 requests can impact application performance and user experience.

  **Relevant Metrics**:
  - `minio_s3_time_ttfb_seconds_distribution`
  - `minio_s3_requests_waiting_total`

  **Alert Examples**:
  
  - **Alert for High Time to First Byte (TTFB)** (over 500ms):
    ```yaml
    - alert: MinIO_High_TTFB
      expr: avg(minio_s3_time_ttfb_seconds_distribution{juju_application="minio"}) > 0.5
      for: 5m
      labels:
        severity: medium
      annotations:
        description: "The average time to first byte (TTFB) for S3 requests is above 500ms."
    ```

  - **Alert for S3 Requests Waiting Too Long**:
    ```yaml
    - alert: MinIO_S3_Requests_Waiting
      expr: minio_s3_requests_waiting_total > 10
      for: 5m
      labels:
        severity: high
      annotations:
        description: "There are more than 10 S3 requests waiting in the queue."
    ```

---

### 4. **Process and Resource Exhaustion**

- **Failure Mode**: Resource exhaustion (CPU, memory, file descriptors, etc.) can cause the MinIO process to become unresponsive or crash.

  **Relevant Metrics**:
  - `minio_node_process_cpu_total_seconds`
  - `minio_node_process_resident_memory_bytes`
  - `minio_node_file_descriptor_limit_total`
  - `minio_node_file_descriptor_open_total`

  **Alert Examples**:
  
  - **Alert for High CPU Usage**:
    ```yaml
    - alert: MinIO_High_CPU_Usage
      expr: minio_node_process_cpu_total_seconds > 3600
      for: 5m
      labels:
        severity: high
      annotations:
        description: "MinIO process has been consuming more than 1 hour of CPU time."
    ```

  - **Alert for High Memory Usage** (more than 4GB):
    ```yaml
    - alert: MinIO_High_Memory_Usage
      expr: minio_node_process_resident_memory_bytes > 4 * 1024 * 1024 * 1024
      for: 5m
      labels:
        severity: high
      annotations:
        description: "MinIO process is using more than 4GB of memory."
    ```

  - **Alert for Too Many Open File Descriptors**:
    ```yaml
    - alert: MinIO_Too_Many_Open_File_Descriptors
      expr: minio_node_file_descriptor_open_total > minio_node_file_descriptor_limit_total * 0.9
      for: 5m
      labels:
        severity: high
      annotations:
        description: "MinIO process has opened more than 90% of the allowed file descriptors."
    ```

---

### 5. **Health and System Metrics Issues**

- **Failure Mode**: Issues with MinIO's internal processes or health (e.g., a stalled process, insufficient resources, etc.).

  **Relevant Metrics**:
  - `minio_node_go_routine_total`
  - `minio_node_process_uptime_seconds`
  - `minio_node_syscall_read_total`
  - `minio_node_syscall_write_total`
  
  **Alert Examples**:
  
  - **Alert for High Number of Go Routines** (potential memory leak or excessive concurrency):
    ```yaml
    - alert: MinIO_High_Go_Routines
      expr: minio_node_go_routine_total > 1000
      for: 5m
      labels:
        severity: medium
      annotations:
        description: "MinIO process has more than 1000 Go routines running."
    ```

  - **Alert for MinIO Process Uptime** (if it's been up for too long without restarting):
    ```yaml
    - alert: MinIO_Process_Uptime
      expr: minio_node_process_uptime_seconds > 3600 * 24  # 24 hours
      for: 5m
      labels:
        severity: low
      annotations:
        description: "MinIO process has been running for more than 24 hours without a restart."
    ```

  - **Alert for High Syscall Activity** (indicating I/O bottlenecks):
    ```yaml
    - alert: MinIO_High_Syscall_Activity
      expr: minio_node_syscall_read_total > 1000000 or minio_node_syscall_write_total > 1000000
      for: 5m
      labels:
        severity: medium
      annotations:
        description: "MinIO is encountering high syscall activity (read or write) on the system."
    ```

**Comment by misohu** [comment]
Please note that some of the alerts use "magic numbers" for tresholds. I set these based on the best practices I found on the internet. In reality these needs to be adjusted based on customer deployments.

**Comment by orfeas-k** [comment]
Good job Michal, the findings here look really promising.

Regarding the last point about "magic numbers", could we use instead e.g. prometheus  [rate](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) or [irate](https://prometheus.io/docs/prometheus/latest/querying/functions/#irate) functions? They can help us check for increase of percentages. For example,  in `expr: minio_s3_requests_errors_total > 100`,100 seems arbitrary since it could be really large for a small deployment and really small for a large deployment. We could use instead `rate(minio_s3_requests_errors_total[2m]) > 0.1` which means that the errors were increased by 10%. That could be similar for the rest of requests alerts. WDYT?

Could something similar be applied also to: 
* `minio_s3_requests_waiting_total`, unless 10 is a always a big number for having s3 requests waiting.
* Alert for High CPU Usage. I don't really understand this one tbh. Is "MinIO process has been consuming more than 1 hour of CPU time." an indicating factor of the performance? Not sure what the threshold number should be here though if we go with rate/irate.
* `minio_node_syscall_read_total` (Alert for High Syscall Activity)

Regarding "Alert for MinIO Process Uptime", is MinIO process expected to restart frequently?

That being said, we could keep those points and investigate during the implementation or we could explore a bit more and be better prepared for the implementation.

**Comment by misohu** [comment]
Hey @orfeas-k thanks for your comment. I worked on it today a little bit and made these adjusted alerts.

## 1. Disk or Storage Issues

### Failure Mode
MinIO running out of disk space can lead to failed writes or degraded performance.

### Relevant Metrics
- `minio_node_disk_free_bytes`
- `minio_node_disk_used_bytes`
- `minio_node_disk_total_bytes`
- `minio_cluster_disk_free_inodes`

### Alerts

```yaml
- alert: MinIO_Low_Disk_Space
  expr: minio_node_disk_free_bytes < 10 * 1024 * 1024 * 1024
  for: 5m
  labels:
    severity: critical
  annotations:
    description: "MinIO node has less than 10GB of free disk space."
```

```yaml
- alert: MinIO_High_Disk_Usage
  expr: (minio_node_disk_used_bytes / minio_node_disk_total_bytes) > 0.9
  for: 5m
  labels:
    severity: high
  annotations:
    description: "MinIO node has over 90% of its disk space used."
```

---

## 2. S3 Request Failures

### Failure Mode
S3 request errors often indicate internal errors, misconfigurations, or connectivity issues.

### Relevant Metrics
- `minio_s3_requests_errors_total`
- `minio_s3_requests_rejected_auth_total`
- `minio_s3_requests_rejected_invalid_total`

### Alerts

```yaml
- alert: MinIO_S3_Request_Errors
  expr: rate(minio_s3_requests_errors_total[2m]) / rate(minio_s3_requests_total[2m]) > 0.1
  for: 5m
  labels:
    severity: high
  annotations:
    description: "More than 10% of S3 requests are resulting in errors."
```

```yaml
- alert: MinIO_S3_Request_Auth_Failures
  expr: rate(minio_s3_requests_rejected_auth_total[2m]) > 1
  for: 5m
  labels:
    severity: high
  annotations:
    description: "MinIO is experiencing >1 auth failure/sec in S3 requests."
```

```yaml
- alert: MinIO_S3_Request_Invalid
  expr: rate(minio_s3_requests_rejected_invalid_total[2m]) > 1
  for: 5m
  labels:
    severity: high
  annotations:
    description: "MinIO is rejecting >1 invalid S3 request per second."
```

---

## 3. High S3 Request Latency

### Failure Mode
Slow S3 response times impact application performance and user experience.

### Relevant Metrics
- `minio_s3_time_ttfb_seconds_distribution`
- `minio_s3_requests_waiting_total`

### Alerts

```yaml
- alert: MinIO_High_TTFB
  expr: avg_over_time(minio_s3_time_ttfb_seconds_distribution[2m]) > 0.5
  for: 5m
  labels:
    severity: medium
  annotations:
    description: "Average S3 request TTFB is above 500ms."
```

```yaml
- alert: MinIO_S3_Requests_Waiting
  expr: rate(minio_s3_requests_waiting_total[2m]) > 5
  for: 5m
  labels:
    severity: high
  annotations:
    description: "More than 5 S3 requests are persistently waiting per second."
```

---

## 4. Resource Exhaustion

### Failure Mode
Resource exhaustion (CPU, memory, file descriptors) can make MinIO unresponsive or unstable.

### Relevant Metrics
- `minio_node_process_cpu_total_seconds`
- `minio_node_process_resident_memory_bytes`
- `minio_node_file_descriptor_*`

### Alerts

```yaml
- alert: MinIO_High_CPU_Usage
  expr: rate(minio_node_process_cpu_total_seconds[2m]) > 0.8
  for: 5m
  labels:
    severity: high
  annotations:
    description: "MinIO is consuming >80% CPU usage per core."
```

```yaml
- alert: MinIO_High_Memory_Usage
  expr: minio_node_process_resident_memory_bytes > 4 * 1024 * 1024 * 1024
  for: 5m
  labels:
    severity: high
  annotations:
    description: "MinIO process is using more than 4GB of memory."
```

```yaml
- alert: MinIO_Too_Many_Open_File_Descriptors
  expr: (minio_node_file_descriptor_open_total / minio_node_file_descriptor_limit_total) > 0.9
  for: 5m
  labels:
    severity: high
  annotations:
    description: "MinIO is using over 90% of its allowed file descriptors."
```

---

## 5.  Internal Health & Process Indicators

### Failure Mode
MinIO stalls, excessive concurrency, or system-level I/O overload.

### Relevant Metrics
- `minio_node_go_routine_total`
- `minio_node_syscall_read_total`, `minio_node_syscall_write_total`
- `minio_node_process_uptime_seconds`

### Alerts

```yaml
- alert: MinIO_High_Go_Routines
  expr: minio_node_go_routine_total > 1000
  for: 5m
  labels:
    severity: medium
  annotations:
    description: "MinIO has more than 1000 Go routines — possible goroutine leak."
```

```yaml
- alert: MinIO_High_Syscall_Activity
  expr: rate(minio_node_syscall_read_total[2m]) > 10000 or rate(minio_node_syscall_write_total[2m]) > 10000
  for: 5m
  labels:
    severity: medium
  annotations:
    description: "MinIO is experiencing high read/write syscall rates."
```

```yaml
- alert: MinIO_Process_Running_Long
  expr: minio_node_process_uptime_seconds > 3600 * 24 * 30
  for: 5m
  labels:
    severity: low
  annotations:
    description: "MinIO process has been running for over 30 days without a restart."
```

---
